version: "3.8"

services:
  rl_research:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: rl-research:latest
    command: /bin/bash -c "python train.py task=dog-run compile=true"
    # command: echo ${WANDB_API_KEY}
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=0
      - WANDB_API_KEY=/run/secrets/wandb_api_key
    secrets:
      - wandb_api_key
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

secrets:
  wandb_api_key:
    file: wandb_api_key.txt
