version: "3.8"

services:
  rl_research:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: rl-research:latest
    command: /bin/bash -c "python -u train.py task=kinova compile=false"
    # command: tail -f /dev/null
    env_file: "tdmpc2.env"
    volumes:
      - ./tdmpc2/:/root/tdmpc2/tdmpc2/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
